spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/library_management
    username: postgres
    password: ${DB_PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug